spring.datasource.url = jdbc:mysql://root:PmOoTcSWaVrttWNNFOXuzwwpAiniQQUf@kodama.proxy.rlwy.net:19372/railway
spring.datasource.username = root
spring.datasource.password = PmOoTcSWaVrttWNNFOXuzwwpAiniQQUf


spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans = true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.static-path-pattern=/**

payos.client-id=603034c2-3e27-4071-bccd-997074083fc7
payos.api-key=e7c8a942-7ea4-4f68-b122-30259f8cbe28
payos.checksum-key=3662a2f56de5fd2329a56d06f7a5236b3a121c05ef22d116ff1535c2504831a2

app.frontend-url=http://localhost:8080
